language: python

python:
  - 2.7

env:
  - DJANGO=1.6.11 MIGRATE='true'
  - DJANGO=1.7.7 MIGRATE='./manage.py migrate'

branches:
  only:
    - master

install:
  - pip install -q Django==$DJANGO
  - pip install -r example/requirements.txt
  - python setup.py -q install

services:
  - redis-server

before_script:
  - pip freeze

script:
  - cd example && python $MIGRATE && python ./manage.py test server --settings=server.settings
