language: python

python:
  - 2.7

env:
  - DJANGO=1.7.9 MIGRATE='python ./manage.py migrate'
  - DJANGO=1.8.3 MIGRATE='python ./manage.py migrate'

branches:
  only:
    - master

install:
  - pip install -q Django==$DJANGO
  - pip install -r example/requirements.txt
  - python setup.py -q install

before_script:
  - pip freeze

script:
  - cd example && $MIGRATE && python ./manage.py test server --settings=server.settings
